# Generated by Django 5.0.6 on 2024-06-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
