# Generated by Django 5.0.6 on 2024-06-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_usuariopersonalizado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
