# Generated by Django 5.0.6 on 2024-06-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_screenshot_delete_imagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
