# Generated by Django 5.0.6 on 2024-06-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='imagen',
            field=models.ImageField(default=None, upload_to='static/'),
        ),
    ]
