# Generated by Django 5.0.6 on 2024-06-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_pagina_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
