# Generated by Django 5.0.6 on 2024-06-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mi_campo',
            new_name='birthdate',
        ),
    ]
