# Generated by Django 5.0.6 on 2024-06-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_remove_customuser_birthdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
