# Generated by Django 5.0.6 on 2024-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='imagen',
            field=models.ImageField(default=None, upload_to='static/'),
        ),
    ]
