# Generated by Django 5.0.6 on 2024-06-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_task_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
