# Generated by Django 5.0.6 on 2024-06-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_alter_task_description_alter_task_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='imagen',
        ),
    ]
