# Generated by Django 5.0.6 on 2024-06-23 19:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_remove_task_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None),
        ),
    ]
