# Generated by Django 5.0.6 on 2024-06-24 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
